ADDED HM1
Masiaka8/SauceDemo_QA22_Maksim_Shestozub pull request #2
Opened 2022-12-14 23:45 UTC by Masiaka8

Моих знаний не хватает что б тесты не падали. Мне нужна помощь.

2022-12-15 10:41 UTC, voropa requested changes

2022-12-15 10:41 UTC, voropa commented on src/test/java/pages/CheckoutPage.java
> +    private final static By CANCEL_BUTTON = By.cssSelector("#cancel");
Старайтесь делать все единообразно: либо все локатаоры private  By, либо private final static By, а у вас в перемешку

2022-12-15 10:41 UTC, voropa commented on src/test/java/pages/LoginPage.java
> +    private By PASSWORD_INPUT_LOCATOR = By.cssSelector("#password");
То же самое тут

2022-12-15 10:41 UTC, voropa commented on src/test/java/pages/ProductsPage.java
> +    private final static By ITEM_BUTTON = By.xpath("//div[@class='inventory_item_name']");
Тут тоже в локаторы нужно добвить ".", как и в ITEM_PRICE

2022-12-15 10:41 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +
Вот тут вы збыли проиницилизировать вот эти обьекты:
  shoppingCartPage;
    productsDetailPage;
    checkoutPage;
    checkoutOverview;
    
    Вы их только обьявили выше, но не проиниициаализировали через new ()
    
    Вероятно поэтому и ловите NullPointerException и тесты не работаают

2022-12-15 23:16 UTC, Masiaka8 commented
Спасибо, исправил. Осталось падать 2 теста 
![Screenshot_2](https://user-images.githubusercontent.com/114669783/207986923-c0c071bd-1924-4b17-ae35-e3db4cd03b39.png)
![Screenshot_1](https://user-images.githubusercontent.com/114669783/207986945-ec08940f-a370-4566-8b46-a2d79ff43f0f.png)

2022-12-16 08:10 UTC, voropa commented
> Спасибо, исправил. Осталось падать 2 теста ![Screenshot_2](https://user-images.githubusercontent.com/114669783/207986923-c0c071bd-1924-4b17-ae35-e3db4cd03b39.png) ![Screenshot_1](https://user-images.githubusercontent.com/114669783/207986945-ec08940f-a370-4566-8b46-a2d79ff43f0f.png)

Ну тут уже я не знаю, чего падает, запускайте в дебаге, смотрите, где ошибка

2022-12-20 21:48 UTC, voropa approved these changes

2022-12-21 12:00 UTC, merged